### ISSUE TITLE
Well how about more than 1 reporting system per replay

### ISSUE THREAD

**Issue by byterock** [DavidIAm/Replay#1]
I was playing about today and notices that I will need both a 
Mongo reporting system for on set of rules and a 'File' reporting system.

Depending on the Biz rule I am playing with.

I will see if I can make selection of the reporting system based on the rule.  Now does that break anything in the model I wonder??

**Comment by DavidIAm** [comment]
It occurs to me there is an interesting configuration matter to be 'which rules are being run in which reporting engine'

**Comment by DavidIAm** [comment]
This feature now exists.  It enables you to set a policy based on whatever you like to select among any of the report engines you have installed.

to use it, set a new default 'ReportSelectorClass' under 'Defaults' in the replay configuration hash, holding the classname of the report selector you have created.

The default report selector 'Replay::ReportEngine::Selector' just returns the default report engine - which is defined under the key 'ReportEngine' under 'Defaults' in the replay configuration hash.

The report selector must use the role Replay::Role::ReportSelector which provides some various information about reporting engines that are configured and requires you to implement the function 'select' which accepts an idkey and expects a report engine object in return.  Of particular note, the RuleSource is available via the role which lets you create your own augmentation of rules by adding a method to them that lets them specifically indicate which report engine should be used with them.
