### ISSUE TITLE
Ouch (Crypt-SSLeay) bit us in the arse

### ISSUE THREAD

**Issue by byterock** [DavidIAm/Replay#2]
Getting a bunch of these 

500 Can't connect to sns.us-east-1.amazonaws.com:443 (Crypt-SSLeay can't verify hostnames) at /usr/lib/perl5/site_perl/5.8.8/Replay/EventSystem/AWSQueue.pm line 248.

Now the topic name is ok
topicName->prod_replay_origin

and in the end what I think we had to do was add

use Perl::Version;
++use Amazon::SNS;
use Try::Tiny;

Replay::EventSystem::AWSQueue

**Comment by byterock** [comment]
So far it has same error has not come up will give it overnight to see if it is a fix

**Comment by byterock** [comment]
And now it still errors very odd
will have to try something else me guess

**Comment by byterock** [comment]
Sorry that is not what I did I added something else

use Perl::Version;
++use IO::Socket::SSL;
use Amazon::SNS;

**Comment by DavidIAm** [comment]
I see this in the current code so closing.
