### ISSUE TITLE
A reduce that doesn't keep state can return undef

### ISSUE THREAD

**Issue by DavidIAm** [DavidIAm/Replay#4]
When you write a rule that has no state left to record for a key, the reduce function should return empty list OR undef to indicate state delete

At this time state delete only happens with an empty list.  We should have it also do this if it returns a single element list with the value undef

**Comment by byterock** [comment]
I did change my code to return and empty list like this

-- $out;
++ @out;

...bla bla bla

--return  $out;
++return @out;

and that stopped the extra row from appearing in the mongo

**Comment by byterock** [comment]
Just a quick update this does not work with

my $out = {};  

or

my $out = [ ];  

and  we do not give a return value by falling out of the sub



To say the least I am super-per-plexi-ated over this as it is a little confusing

For not reporting rules (ie EPOD)

Does not add an record to mongo when an empty array or hash (just checked that) is returned

but does add a record  with an empty array ref, or hash ref

For reporting rules (Epod Billing)

If you return an hash ref it works 

But

If you return a Hash or an Array it fails 

So a little inconstant  on what it accepts as a valid expected return;


Oh one other point Found a way for it to get into an endless loop (return an ARRAY of one hash ref)

we might want to check that out as well

Can create a rule stub for this if youwant

**Comment by byterock** [comment]
Interseting

The one I where I get an endless look the atoms comming back are



atoms=$VAR1 = [
          27,
          'count',
          49830,
          'bytes',
          {
            'bytes' => 1665,
            'count' => 1
          },
          {
            'count' => 1,
            'bytes' => 1665
          },
          {
            'count' => 1,
            'bytes' => 2040
          },
          {
            'count' => 1,
            'bytes' => 1665
          },
          {
            'bytes' => 2040,
            'count' => 1
          },
          {
            'bytes' => 2040,
            'count' => 1
          },
          {
            'bytes' => 2040,
            'count' => 1
          }
        ];

So that send as an arrry bugdered the data on the back end as that first recors should not be there that is the total for they window.

At least I know how to recreate

**Comment by DavidIAm** [comment]
Added this feature to the system, in that it now can be set to ignore single unit lists of undef and also that it can flatten arrayrefs that are handed to it, as both of these things might be done by programmers not quite understanding the intended API.

Right now both of these behaviors are enabled.

You can set the config hash value 'null_filter_enabled => 0' if you wish a list consisting of a single undef value to be a valid state document.  otherwise it shall be considered an empty list and the state transitions to its 'no longer relevant' delete state.

You can set the config hash value 'arrayref_flatten_enabled => 0' if you wish arrayrefs to be valid document elements.  otherwise, any root level array refs in the returned list from the reduce function will be flattened to their individual elements.
