### ISSUE TITLE
Reducer clarity

### ISSUE THREAD

**Issue by byterock** [DavidIAm/Replay#8]
Ok for one rule I have this in the reduce sub
```
sub reduce {
    my ( $self, $emitter, @atoms ) = @_;
    my $out;

    foreach my $item (@atoms) {
        $out->{count} += $item->{count};
        $out->{bytes} += $item->{bytes};
        $out->{pages} += $item->{pages};
    }

    return $out;
}
```
so it is returning a hash and it works

in other I just return and empty array if
```
sub reduce {
    my ( $self, $emitter, @atoms ) = @_;
    my @out;

    foreach my $item (@atoms) {
    bla bla bla..
    }

    return @out;
}
```

now I just found this one 
```
sub reduce {
    my ( $self, $emitter, @atoms ) = @_;
    my $out;
    foreach my $event (@atoms) {

        if ( !exists( $event->{event} ) ) {
            $out = $event;
        }
        else {
               my $scac = $self->getSCAC( $event );
                next
                  unless ($scac);
                 bla... bla... bla,,
            }
        }
    }
    return $out;
}
```

The point being here I might exit early from the foreach before anything is added to the $out??

So would it be best to check that $out is undef and return an empty array insted ie
```
        else {
               my $scac = $self->getSCAC( $event );
                next
                  unless ($scac);
                 bla... bla... bla,,
            }
        }
    }
    if (keys(%{$out}){
    return $out;
    else{
my @nothing
return @nothing
    
    }
}
```

**Comment by DavidIAm** [comment]
If you return an empty list you are saying 'nothing about the input of this state previously is relevant to it now' - basically you're clearing the state.  The 'current' version of the output report will no longer be available (only frozen output copies will remain). If that is what you desire in this case, then yes, that is what you should return.

**Comment by DavidIAm** [comment]
in the case of returning the hash, what you're actually returning is a list consisting of one hash reference, which is a legitimate (and probably fairly frequent) state.

**Comment by DavidIAm** [comment]
This seems fairly clear...
