### ISSUE TITLE
package Replay::Role::Envelope

### ISSUE THREAD

**Issue by byterock** [DavidIAm/Replay#9]
When you get a chance can you look at the marshal sub

sub marshall {
    my $self       = shift;
    my $buffer     = q();
    my $row        = 1;
    my $layers     = {};
    my %attributes = map { $_->{name} => $_ } $self->meta->get_all_attributes;
    foreach my $attr (sort { $a cmp $b } keys %attributes) {

        my $field = $attributes{$attr};

        do {
            warn "NO SUCH ATTRBUTE $attr IN META OF "
                . ref($self) . " - "
                . Dumper ref $attributes{$attr}
                and next;
        } unless defined $field;
        my $thislayer
            = ($field->can('description') ? $field->description->{layer} : '')
            || 'sloppy';

        my $node = $layers->{$thislayer} ||= {};

        my $value = $self->$attr
            ; #$field->can('associated_role') ? $field->associated_role->get_value($self) : $field->get_value($self);
        next if not defined $value;

        $node->{$attr} = $value;
    }
    my $curmessage = $layers->{envelope}{Message} ||= {};
    %{$curmessage} = (%{$curmessage}, %{ $layers->{message} || {} });
    return $layers->{envelope};
}

For example $node is set but it inside a foreach so I do not know what it is suppose to do??

**Comment by byterock** [comment]
as well is not this a circular reff

sub _build_uuid {    ## no critic (ProhibitUnusedPrivateSubroutines)
    my $self = shift;
    my $ug   = Data::UUID->new;
    return $ug->to_string($ug->create());
}

??

Looking for that memory leak

**Comment by DavidIAm** [comment]
Simplified to same functionality: 

```
sub marshall {
    my $self       = shift;                                                             my $buffer     = q();
    my $row        = 1;
    my $layers     = {};
    my %attributes = map { $_->{name} => $_ } $self->meta->get_all_attributes;
    foreach my $attr ( sort { $a cmp $b } keys %attributes ) {

        my $field = $attributes{$attr};

        do {
            warn "NO SUCH ATTRBUTE $attr IN META OF "
                . ref($self) . " - "
                . Dumper ref $attributes{$attr}
                and next;
        } unless defined $field;

        $layers->{ $self->layer_name_for_field($field) }{$attr} = $self->$attr
            if defined $self->$attr;
    }
    %{$layers->{envelope}{Message}} = (
        %{ $layers->{envelope}{Message} || {} },
        %{ $layers->{message} || {} }
    );
    return $layers->{envelope};
}


```

**Comment by DavidIAm** [comment]
As for build_uuid... no, it isn't.  The to_string method is not available on the output of the create function.  Its merely a formatter that has to be handed the uuid that its making a string out of.

**Comment by byterock** [comment]
Ok thank  
Been looking into the memory leaks
and below might be a better way to write it up

sub marshall {
    my $self       = shift;                                                             
   my $buffer     = q();
    my $row        = 1;
    my $layers     = {};
    my %attributes = map { $_->{name} => $_ } $self->meta->get_all_attributes;
    foreach my $attr ( sort { $a cmp $b } keys %attributes ) {

        my $field = $attributes{$attr};

        do {
            warn "NO SUCH ATTRBUTE $attr IN META OF "
                . ref($self) . " - "
                . Dumper ref $attributes{$attr}
                and next;
        } unless defined $field;
++        my $value = $self->$attr;
++       $layers->{ $self->layer_name_for_field($field) }{$attr} = $value
            if defined $self->$attr;
    }
    %{$layers->{envelope}{Message}} = (
        %{ $layers->{envelope}{Message} || {} },
        %{ $layers->{message} || {} }
    );
    return $layers->{envelope};
}

What I will do is see if the new code leaks and my little 'fix'  helps any

S
